/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;
//Testing
//        for each of the Feature Tasks.
public class AppTest {

}
