/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import quotes.bookQuote.Quote;

import java.io.*;
import java.util.*;

public class App {


    public static void main(String[] args) {


    }
}